### ISSUE TITLE
Error while installing MMM-AssistantMk2

### ISSUE THREAD

**Issue by ravening** [makepluscode/rpi-tutorial-advanced#11]
I was following the steps you have mentioned and got the error while running the command in MMM-AssistantMk2 folder

./node_modules/.bin/electron-rebuild

The stack trace is given below. Can you help me with this issue?

<img width="1275" alt="Screen Shot 2019-07-06 at 00 40 01" src="https://user-images.githubusercontent.com/10645273/60747615-a25dc880-9f86-11e9-9306-025e89dc58e7.png">

**Comment by guzand3r** [comment]
Thanks for this module !... but same error here, i precise i've installed my MM on a Pi 4, i don't know if it helps.

**Comment by guzand3r** [comment]
See in issue section for MMM-AssistantMk2 : "In Raspbian Buster, grpc couldn't be compiled for electron yet. Use stretch or just wait for dependencies being stable."
I use Buster so i have to wait...

**Comment by ravening** [comment]
yes saw that. Thanks for pointing it out. I will close this thread.
